"""CSV and JSON output utilities for Monte Carlo backtest results.

This module provides helpers for writing Monte Carlo trial results to CSV
files and for exporting the best-found parameters back to JSON config files.
"""

import json
import os
from typing import Any

from functions.logger_config import get_logger

logger = get_logger(__name__, log_file="pytaaa_backtest_montecarlo.log")

#############################################################################
# CSV column header (matches original PyTAAA_backtest_sp500_pine_refactored)
#############################################################################

_CSV_COLUMNS = (
    "run,trial,"
    "Number stocks,"
    "monthsToHold,"
    "LongPeriod,"
    "MA1,"
    "MA2,"
    "MA3,"
    "volatility min,volatility max,"
    "max_weight_factor,"
    "min_weight_factor,"
    "absolute_max_weight,"
    "Portfolio Final Value,"
    "stddevThreshold,"
    "sma2factor,"
    "rank Threshold (%),"
    "sma_filt_val,"
    "Portfolio std,Portfolio Sharpe,"
    "begin date for recent performance,"
    "Portfolio Ann Gain - recent,"
    "Portfolio Sharpe - recent,"
    "B&H Ann Gain - recent,B&H Sharpe - recent,"
    "Sharpe 15 Yr,"
    "Sharpe 10 Yr,"
    "Sharpe 5 Yr,"
    "Sharpe 3 Yr,"
    "Sharpe 2 Yr,"
    "Sharpe 1 Yr,"
    "Return 15 Yr,"
    "Return 10 Yr,"
    "Return 5 Yr,"
    "Return 3 Yr,"
    "Return 2 Yr,"
    "Return 1 Yr,"
    "CAGR 15 Yr,"
    "CAGR 10 Yr,"
    "CAGR 5 Yr,"
    "CAGR 3 Yr,"
    "CAGR 2 Yr,"
    "CAGR 1 Yr,"
    "B&H CAGR 15 Yr,"
    "B&H CAGR 10 Yr,"
    "B&H CAGR 5 Yr,"
    "B&H CAGR 3 Yr,"
    "B&H CAGR 2 Yr,"
    "B&H CAGR 1 Yr,"
    "Avg Drawdown 15 Yr,"
    "Avg Drawdown 10 Yr,"
    "Avg Drawdown 5 Yr,"
    "Avg Drawdown 3 Yr,"
    "Avg Drawdown 2 Yr,"
    "Avg Drawdown 1 Yr,"
    "beatBuyHoldTest,"
    "beatBuyHoldTest2,"
    "param varied"
)


def get_csv_header() -> str:
    """Return the CSV column header string.

    Returns:
        Single-line header string with all column names separated by
        commas, terminated by a newline.

    Example:
        >>> header = get_csv_header()
        >>> "Portfolio Sharpe" in header
        True
    """
    return _CSV_COLUMNS + "\n"


def format_csv_row(
    runnum: str,
    iter_num: int,
    params: dict,
    metrics: dict,
) -> str:
    """Format a single CSV result row from parameters and computed metrics.

    Args:
        runnum: Run identifier string (e.g. ``run2501a``).
        iter_num: Zero-based trial index.
        params: Parameter dict generated by ``generate_random_parameters``.
        metrics: Computed performance metrics dict.  Expected keys:
            FinalValue, PortfolioStd, PortfolioSharpe, targetdate,
            AnnGainRecent, SharpeRecent, BHAnnGainRecent, BHSharpeRecent,
            Sharpe15Yr … Sharpe1Yr, Return15Yr … Return1Yr,
            CAGR15Yr … CAGR1Yr, BuyHoldCAGR15Yr … BuyHoldCAGR1Yr,
            Drawdown15Yr … Drawdown1Yr, beatBuyHoldTest, beatBuyHoldTest2.

    Returns:
        CSV row string terminated by a newline.

    Example:
        >>> row = format_csv_row("run2501a", 0, params, metrics)
        >>> row.endswith("\\n")
        True
    """

    def _f(val: Any, fmt: str = "") -> str:
        """Format value, returning 'nan' string for None/NaN."""
        try:
            if val is None:
                return "nan"
            if fmt:
                return format(val, fmt)
            return str(val)
        except (TypeError, ValueError):
            return "nan"

    row = (
        runnum + ","
        + str(iter_num) + ","
        + str(params.get("numberStocksTraded", "")) + ","
        + str(params.get("monthsToHold", "")) + ","
        + str(params.get("LongPeriod", "")) + ","
        + str(params.get("MA1", "")) + ","
        + str(params.get("MA2", "")) + ","
        + str(params.get("MA3", "")) + ","
        + str(params.get("riskDownside_min", "")) + ","
        + str(params.get("riskDownside_max", "")) + ","
        + _f(params.get("max_weight_factor"), "5.3f") + ","
        + _f(params.get("min_weight_factor"), "5.3f") + ","
        + _f(params.get("absolute_max_weight"), "5.3f") + ","
        + str(metrics.get("FinalValue", "")) + ","
        + _f(params.get("stddevThreshold"), "5.3f") + ","
        + _f(params.get("sma2factor"), "5.3f") + ","
        + _f(params.get("rankThresholdPct"), ".1%") + ","
        + _f(params.get("sma_filt_val"), "5.5f") + ","
        + str(metrics.get("PortfolioStd", "")) + ","
        + str(metrics.get("PortfolioSharpe", "")) + ","
        + str(metrics.get("targetdate", "")) + ","
        + str(metrics.get("AnnGainRecent", "")) + ","
        + str(metrics.get("SharpeRecent", "")) + ","
        + str(metrics.get("BHAnnGainRecent", "")) + ","
        + str(metrics.get("BHSharpeRecent", "")) + ","
        + _f(metrics.get("Sharpe15Yr"), "5.2f") + ","
        + _f(metrics.get("Sharpe10Yr"), "5.2f") + ","
        + _f(metrics.get("Sharpe5Yr"), "5.2f") + ","
        + _f(metrics.get("Sharpe3Yr"), "5.2f") + ","
        + _f(metrics.get("Sharpe2Yr"), "5.2f") + ","
        + _f(metrics.get("Sharpe1Yr"), "5.2f") + ","
        + _f(metrics.get("Return15Yr"), "5.4f") + ","
        + _f(metrics.get("Return10Yr"), "5.4f") + ","
        + _f(metrics.get("Return5Yr"), "5.4f") + ","
        + _f(metrics.get("Return3Yr"), "5.4f") + ","
        + _f(metrics.get("Return2Yr"), "5.4f") + ","
        + _f(metrics.get("Return1Yr"), "5.4f") + ","
        + _f(metrics.get("CAGR15Yr"), ".4f") + ","
        + _f(metrics.get("CAGR10Yr"), ".4f") + ","
        + _f(metrics.get("CAGR5Yr"), ".4f") + ","
        + _f(metrics.get("CAGR3Yr"), ".4f") + ","
        + _f(metrics.get("CAGR2Yr"), ".4f") + ","
        + _f(metrics.get("CAGR1Yr"), ".4f") + ","
        + _f(metrics.get("BuyHoldCAGR15Yr"), ".4f") + ","
        + _f(metrics.get("BuyHoldCAGR10Yr"), ".4f") + ","
        + _f(metrics.get("BuyHoldCAGR5Yr"), ".4f") + ","
        + _f(metrics.get("BuyHoldCAGR3Yr"), ".4f") + ","
        + _f(metrics.get("BuyHoldCAGR2Yr"), ".4f") + ","
        + _f(metrics.get("BuyHoldCAGR1Yr"), ".4f") + ","
        + _f(metrics.get("Drawdown15Yr"), "5.4f") + ","
        + _f(metrics.get("Drawdown10Yr"), "5.4f") + ","
        + _f(metrics.get("Drawdown5Yr"), "5.4f") + ","
        + _f(metrics.get("Drawdown3Yr"), "5.4f") + ","
        + _f(metrics.get("Drawdown2Yr"), "5.4f") + ","
        + _f(metrics.get("Drawdown1Yr"), "5.4f") + ","
        + _f(metrics.get("beatBuyHoldTest"), "5.3f") + ","
        + _f(metrics.get("beatBuyHoldTest2"), ".2%") + ","
        + str(params.get("paramNumberToVary", ""))
        + "\n"
    )
    return row


def write_csv_header(outfilename: str) -> None:
    """Write the CSV column header to a new (or truncated) file.

    Args:
        outfilename: Absolute path to the output CSV file.  The file is
            opened in write mode, overwriting any existing content.

    Example:
        >>> write_csv_header("/tmp/results.csv")
    """
    os.makedirs(os.path.dirname(outfilename) or ".", exist_ok=True)
    with open(outfilename, "w") as fid:
        fid.write(get_csv_header())
    logger.debug("CSV header written to %s", outfilename)


def append_csv_row(outfilename: str, row: str) -> None:
    """Append a single CSV data row to an existing file.

    Args:
        outfilename: Absolute path to the output CSV file.
        row: Formatted CSV row string (should end with newline).

    Example:
        >>> append_csv_row("/tmp/results.csv", "run2501a,0,...\\n")
    """
    with open(outfilename, "a") as fid:
        fid.write(row)


def export_optimized_parameters(
    base_json_fn: str,
    optimized_params: dict,
    output_dir: str,
    model_id: str,
    date_str: str,
) -> str:
    """Export optimized parameters to a JSON file.

    Reads the base JSON configuration, updates the ``Valuation`` section
    with the provided optimized parameters, and writes a new JSON file
    to ``output_dir``.

    Args:
        base_json_fn: Path to the base JSON configuration file.
        optimized_params: Dictionary of optimized parameter values to
            merge into the ``Valuation`` section.
        output_dir: Directory in which to write the output JSON file.
        model_id: Model identifier used in the output filename.
        date_str: Date string used in the output filename.

    Returns:
        Absolute path to the written JSON file.

    Raises:
        FileNotFoundError: If ``base_json_fn`` does not exist.

    Example:
        >>> path = export_optimized_parameters(
        ...     "config.json", {"LongPeriod": 412}, "/tmp/out",
        ...     "sp500_pine", "2025-6-1"
        ... )
    """
    with open(base_json_fn, "r") as fid:
        config = json.load(fid)

    valuation = config.get("Valuation", {})
    valuation.update(optimized_params)
    config["Valuation"] = valuation

    filename = f"{model_id}_optimized_{date_str}.json"
    output_path = os.path.join(output_dir, filename)

    os.makedirs(output_dir, exist_ok=True)
    with open(output_path, "w") as fid:
        json.dump(config, fid, indent=4)

    logger.info("Optimized parameters exported to %s", output_path)
    return output_path
